FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /frontend

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8502

CMD ["streamlit", "run", "frontend.py", "--server.port=8502", "--server.address=0.0.0.0"]
